% imStart = ['Images01/frame0000.png';...
%     'Images02/frame0000.png';...
%     'Images02/frame0060.png';...
%     'Images03/frame0000.png';...
%     'Images04/frame0000.png';...
%     'Images04/frame0040.png';...
%     'Images05/frame0000.png';...
%     'Images05/frame0100.png'];

res = resRans;


disp('\hline');
for st = 1:size(imStart,1)
    lol = [imStart(st,:)];
    for n = 1:4 % già formattato per latex, lol
        
        lol = [lol, ' & ' num2str(mean(res(st,n,res(st,n,:)>0)),3),'s (',num2str(std(res(st,n,res(st,n,:)>0)),2),'s)'];
        
    end
    disp([lol, '\\ \hline']);
end